-- 1
-- 소속정보 테이블 생성
CREATE TABLE TEAM_INFO (
    TEAM_CODE INT AUTO_INCREMENT PRIMARY KEY COMMENT '소속코드',
    TEAM_NAME VARCHAR(100) NOT NULL COMMENT '소속명',
    TEAM_DETAIL VARCHAR(500) NULL COMMENT '소속상세정보',
    USE_YN CHAR(2) NOT NULL DEFAULT 'Y' CHECK (USE_YN IN ('Y', 'N')) COMMENT '사용여부'
) COMMENT '소속정보';

-- 회원정보 테이블 생성
CREATE TABLE MEMBER_INFO (
    MEMBER_CODE INT AUTO_INCREMENT PRIMARY KEY COMMENT '회원코드',
    MEMBER_NAME VARCHAR(70) NOT NULL COMMENT '회원이름',
    BIRTH_DATE DATE NULL COMMENT '생년월일',
    DIVISION_CODE CHAR(2) NULL COMMENT '구분코드',
    DETAIL_INFO VARCHAR(500) NULL COMMENT '상세정보',
    CONTACT VARCHAR(50) NOT NULL COMMENT '연락처',
    TEAM_CODE INT NOT NULL COMMENT '소속코드',
    ACTIVE_STATUS CHAR(2) NOT NULL DEFAULT 'Y' 
        CHECK (ACTIVE_STATUS IN ('Y', 'N', 'H')) COMMENT '활동상태',
    -- 외래키 설정
    CONSTRAINT FK_MEMBER_TEAM FOREIGN KEY (TEAM_CODE) REFERENCES TEAM_INFO(TEAM_CODE)
) COMMENT '회원정보';

-- 2_1
INSERT INTO TEAM_INFO (TEAM_CODE, TEAM_NAME, TEAM_DETAIL, USE_YN) 
VALUES (1, '음악감상부', '클래식 및 재즈 음악을 감상하는 사람들의 모임', 'Y');

INSERT INTO TEAM_INFO (TEAM_CODE, TEAM_NAME, TEAM_DETAIL, USE_YN) 
VALUES (2, '맛집탐방부', '맛집을 찾아다니는 사람들의 모임', 'N');

INSERT INTO TEAM_INFO (TEAM_CODE, TEAM_NAME, TEAM_DETAIL, USE_YN) 
VALUES (3, '행복찾기부', NULL, 'Y');

-- 2_2
INSERT INTO MEMBER_INFO (MEMBER_CODE, MEMBER_NAME, BIRTH_DATE, DIVISION_CODE, DETAIL_INFO, CONTACT, TEAM_CODE, ACTIVE_STATUS)
VALUES (1, '솔가인', '1990-01-30', '1', '안녕하세요 송가인입니다~', '010-9494-9494', 1, 'H');

INSERT INTO MEMBER_INFO (MEMBER_CODE, MEMBER_NAME, BIRTH_DATE, DIVISION_CODE, DETAIL_INFO, CONTACT, TEAM_CODE, ACTIVE_STATUS)
VALUES (2, '임영웅', '1992-05-03', NULL, '국민아들 임영웅입니다~', 'hero@trot.com', 1, 'Y');

INSERT INTO MEMBER_INFO (MEMBER_CODE, MEMBER_NAME, BIRTH_DATE, DIVISION_CODE, DETAIL_INFO, CONTACT, TEAM_CODE, ACTIVE_STATUS)
VALUES (3, '태진아', NULL, NULL, NULL, '(1급 기밀)', 3, 'Y');

-- 3
SELECT COUNT(*) AS TEAM_MEMBER_COUNT
FROM (
    -- 기술지원부의 대리
    SELECT M.MEMBER_CODE
    FROM MEMBER_INFO M
    JOIN TEAM_INFO T ON M.TEAM_CODE = T.TEAM_CODE
    WHERE T.TEAM_NAME = '기술지원부' AND M.POSITION = '대리'
    
    UNION ALL
    
    -- 인사관리부의 사원
    SELECT M.MEMBER_CODE
    FROM MEMBER_INFO M
    JOIN TEAM_INFO T ON M.TEAM_CODE = T.TEAM_CODE
    WHERE T.TEAM_NAME = '인사관리부' AND M.POSITION = '사원'
    
    UNION ALL
    
    -- 영업부(영업 포함)의 부장
    SELECT M.MEMBER_CODE
    FROM MEMBER_INFO M
    JOIN TEAM_INFO T ON M.TEAM_CODE = T.TEAM_CODE
    WHERE T.TEAM_NAME LIKE '%영업%' AND M.POSITION = '부장'
) AS SUB;  